Repository simonsymhoven/nested-data-reporting-plugin, pull requests merged in 2022-06, with the labels that each got.

#6 Add ci pipeline
  .github/auto_assign.yml
  .github/workflows/assign-pr.yml
  .github/workflows/ci.yml
Labels: github_actions

#11 Add name to release drafter ci pipeline
  .github/workflows/assign-pr.yml
  .github/workflows/release-drafter.yml
Labels: github_actions

#14 Add LICENSE file (MIT)
  LICENSE
Labels: documentation

#16 add action-label-syncer to repository
  .github/labels.yml
  .github/workflows/sync-labels.yml
Labels: github_actions

#12 Trend-Charts at Build Level as Stacked Charts
  src/main/java/io/jenkins/plugins/reporter/charts/AssetTrendChart.java
Labels: enhancement

#17 using one chart class (TrendChart.java) for asset and report
  src/main/java/io/jenkins/plugins/reporter/ReportJobAction.java
  src/main/java/io/jenkins/plugins/reporter/ReportViewModel.java
  src/main/java/io/jenkins/plugins/reporter/charts/ReportTrendChart.java
  src/main/java/io/jenkins/plugins/reporter/charts/TrendChart.java
Labels: java, internal

#20 improve documentation
  README.md
  src/main/java/io/jenkins/plugins/reporter/charts/AssetSeriesBuilder.java
  src/main/java/io/jenkins/plugins/reporter/charts/ReportSeriesBuilder.java
  src/main/java/io/jenkins/plugins/reporter/charts/TrendChart.java
  src/main/java/io/jenkins/plugins/reporter/model/Asset.java
  src/main/java/io/jenkins/plugins/reporter/model/Report.java
Labels: documentation

#19 add new plugin and action icon
  README.md
  src/main/java/io/jenkins/plugins/reporter/ReportJobAction.java
  src/main/webapp/icons/data-reporting-24x24.png
  src/main/webapp/icons/data-reporting-48x48.png
  src/main/webapp/icons/wm-logo-24x24.png
  src/main/webapp/icons/wm-logo-48x48.png
  stocks.csv
Labels: enhancement

#21 using generic json instead of csv as data model
  etc/Jenkinsfile
  etc/result.json
  pom.xml
  src/main/java/io/jenkins/plugins/reporter/PublishReportStep.java
  src/main/java/io/jenkins/plugins/reporter/ReportAction.java
  src/main/java/io/jenkins/plugins/reporter/ReportJobAction.java
  src/main/java/io/jenkins/plugins/reporter/ReportViewModel.java
  src/main/java/io/jenkins/plugins/reporter/charts/AssetSeriesBuilder.java
  src/main/java/io/jenkins/plugins/reporter/charts/ReportSeriesBuilder.java
  src/main/java/io/jenkins/plugins/reporter/charts/TrendChart.java
  src/main/java/io/jenkins/plugins/reporter/model/Asset.java
  src/main/java/io/jenkins/plugins/reporter/model/Item.java
  src/main/java/io/jenkins/plugins/reporter/model/Report.java
  src/main/resources/io/jenkins/plugins/reporter/ReportAction/summary.jelly
  src/main/resources/io/jenkins/plugins/reporter/ReportAction/summary.properties
Labels: java, feature, removed

#22 migrate ReportSeriesBuilder to new json model
  src/main/java/io/jenkins/plugins/reporter/ReportJobAction.java
  src/main/java/io/jenkins/plugins/reporter/ReportViewModel.java
  src/main/java/io/jenkins/plugins/reporter/charts/ReportSeriesBuilder.java
  src/main/java/io/jenkins/plugins/reporter/model/Item.java
  src/main/resources/io/jenkins/plugins/reporter/ReportJobAction/floatingBox.jelly
Labels: enhancement

#23 migrate summary of build to new json model
  src/main/java/io/jenkins/plugins/reporter/ReportAction.java
  src/main/java/io/jenkins/plugins/reporter/charts/ReportSeriesBuilder.java
  src/main/java/io/jenkins/plugins/reporter/model/Report.java
  src/main/resources/io/jenkins/plugins/reporter/Messages.properties
  src/main/resources/io/jenkins/plugins/reporter/ReportAction/summary.jelly
  src/main/resources/io/jenkins/plugins/reporter/ReportAction/summary.properties
Labels: enhancement

#25 migrate ItemSeriesBuilder and ReportViewModel to new json model
  src/main/java/io/jenkins/plugins/reporter/ReportViewModel.java
  src/main/java/io/jenkins/plugins/reporter/charts/AssetSeriesBuilder.java
  src/main/java/io/jenkins/plugins/reporter/charts/ItemSeriesBuilder.java
  src/main/java/io/jenkins/plugins/reporter/charts/TrendChart.java
  src/main/java/io/jenkins/plugins/reporter/model/Report.java
  src/main/resources/io/jenkins/plugins/reporter/ReportViewModel/index.jelly
  src/main/webapp/js/item.js
Labels: enhancement

#26 add color mapping for result items in json model
  README.md
  etc/result.json
  pom.xml
  src/main/java/io/jenkins/plugins/reporter/PublishReportStep.java
  src/main/java/io/jenkins/plugins/reporter/ReportJobAction.java
  src/main/java/io/jenkins/plugins/reporter/ReportViewModel.java
  src/main/java/io/jenkins/plugins/reporter/charts/TrendChart.java
  src/main/java/io/jenkins/plugins/reporter/model/Item.java
  src/main/java/io/jenkins/plugins/reporter/model/Report.java
  src/main/java/io/jenkins/plugins/reporter/model/Result.java
  src/main/resources/io/jenkins/plugins/reporter/ReportAction/summary.jelly
  src/main/resources/io/jenkins/plugins/reporter/ReportViewModel/index.jelly
  src/main/webapp/js/item.js
Labels: feature

#35 Add filter for builds without published report for history charts
  src/main/java/io/jenkins/plugins/reporter/ReportViewModel.java
  src/main/resources/io/jenkins/plugins/reporter/ReportJobAction/floatingBox.jelly
Labels: bug

#37 remove `result` from component item in json model if `items` is present
  README.md
  etc/result.json
  src/main/java/io/jenkins/plugins/reporter/PublishReportStep.java
  src/main/java/io/jenkins/plugins/reporter/ReportViewModel.java
  src/main/java/io/jenkins/plugins/reporter/model/Item.java
  src/main/java/io/jenkins/plugins/reporter/model/Report.java
Labels: enhancement

#38 fix `NullPointerException` for successful builds without `ReportAction`
  src/main/java/io/jenkins/plugins/reporter/ReportViewModel.java
Labels: bug

#41 remove explicit jackson2-api version from pom.xml
  README.md
  pom.xml
Labels: dependencies

#32 implement new ui /data-reporting
  pom.xml
  src/main/java/io/jenkins/plugins/reporter/ReportTableModel.java
  src/main/java/io/jenkins/plugins/reporter/ReportViewModel.java
  src/main/java/io/jenkins/plugins/reporter/model/Item.java
  src/main/java/io/jenkins/plugins/reporter/model/Report.java
  src/main/resources/io/jenkins/plugins/reporter/ReportViewModel/index.jelly
  src/main/resources/io/jenkins/plugins/reporter/ReportViewModel/index.properties
  src/main/webapp/css/custom-style.css
  src/main/webapp/js/item.js
Labels: feature

#44 update README.md & plugin description according the new ui in version…
  README.md
  etc/ui-2.3.0.png
  src/main/resources/index.jelly
Labels: documentation

#49 implement dynamic ui with navigation in data-table
  pom.xml
  src/main/java/io/jenkins/plugins/reporter/PublishReportStep.java
  src/main/java/io/jenkins/plugins/reporter/ReportAction.java
  src/main/java/io/jenkins/plugins/reporter/ReportJobAction.java
  src/main/java/io/jenkins/plugins/reporter/ReportViewModel.java
  src/main/java/io/jenkins/plugins/reporter/ReportXmlStream.java
  src/main/java/io/jenkins/plugins/reporter/charts/ItemSeriesBuilder.java
  src/main/java/io/jenkins/plugins/reporter/charts/ReportSeriesBuilder.java
  src/main/java/io/jenkins/plugins/reporter/model/ItemTableModel.java
  src/main/java/io/jenkins/plugins/reporter/model/Report.java
  src/main/java/io/jenkins/plugins/reporter/model/Result.java
  src/main/resources/io/jenkins/plugins/reporter/PublishReportStep/config.jelly
  src/main/resources/io/jenkins/plugins/reporter/PublishReportStep/help-jsonString.html
  src/main/resources/io/jenkins/plugins/reporter/ReportAction/summary.jelly
  src/main/resources/io/jenkins/plugins/reporter/ReportJobAction/floatingBox.jelly
  src/main/resources/io/jenkins/plugins/reporter/ReportViewModel/index.jelly
  src/main/webapp/css/custom-style.css
  src/main/webapp/js/item.js
Labels: enhancement

#51 add `name` as new readable title property for item to json model
  README.md
  etc/result.json
  src/main/java/io/jenkins/plugins/reporter/ReportAction.java
  src/main/java/io/jenkins/plugins/reporter/ReportViewModel.java
  src/main/java/io/jenkins/plugins/reporter/model/Item.java
  src/main/java/io/jenkins/plugins/reporter/model/ItemTableModel.java
  src/main/java/io/jenkins/plugins/reporter/model/Result.java
Labels: feature

#52 add the dynamic result of item to data-table
  etc/result.json
  etc/ui-2.4.0.png
  src/main/java/io/jenkins/plugins/reporter/ItemViewModel.java
  src/main/java/io/jenkins/plugins/reporter/ReportAction.java
  src/main/java/io/jenkins/plugins/reporter/model/ItemTableModel.java
  src/main/resources/io/jenkins/plugins/reporter/ItemViewModel/index.jelly
  src/main/resources/io/jenkins/plugins/reporter/ItemViewModel/index.properties
Labels: feature

#54 removed jackson2-api.version from pom.xml (relic of echarts-api-plugin update)
  pom.xml
Labels: internal

#55 update `etc/result.json`
  etc/result.json
Labels: documentation

#58 using default color `#E9E9E9` in case color mapping does not exist for a property
  README.md
  pom.xml
  src/main/java/io/jenkins/plugins/reporter/ColorProvider.java
  src/main/java/io/jenkins/plugins/reporter/ItemViewModel.java
  src/main/java/io/jenkins/plugins/reporter/ReportAction.java
  src/main/java/io/jenkins/plugins/reporter/ReportJobAction.java
  src/main/java/io/jenkins/plugins/reporter/charts/TrendChart.java
  src/main/java/io/jenkins/plugins/reporter/model/ItemTableModel.java
  src/main/resources/io/jenkins/plugins/reporter/PublishReportStep/help-jsonString.html
Labels: internal
